//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/_Resources/ScriptableObjects/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""PachinkoInputs"",
            ""id"": ""8a04a21d-9900-4b61-b189-e7107980ec94"",
            ""actions"": [
                {
                    ""name"": ""ResetBall"",
                    ""type"": ""Button"",
                    ""id"": ""8a03c7df-8a20-49cb-b50f-6c6a817c9e83"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""58348818-1c37-4467-9e51-65431c086106"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetBall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PachinkoInputs
        m_PachinkoInputs = asset.FindActionMap("PachinkoInputs", throwIfNotFound: true);
        m_PachinkoInputs_ResetBall = m_PachinkoInputs.FindAction("ResetBall", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PachinkoInputs
    private readonly InputActionMap m_PachinkoInputs;
    private IPachinkoInputsActions m_PachinkoInputsActionsCallbackInterface;
    private readonly InputAction m_PachinkoInputs_ResetBall;
    public struct PachinkoInputsActions
    {
        private @PlayerInputs m_Wrapper;
        public PachinkoInputsActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @ResetBall => m_Wrapper.m_PachinkoInputs_ResetBall;
        public InputActionMap Get() { return m_Wrapper.m_PachinkoInputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PachinkoInputsActions set) { return set.Get(); }
        public void SetCallbacks(IPachinkoInputsActions instance)
        {
            if (m_Wrapper.m_PachinkoInputsActionsCallbackInterface != null)
            {
                @ResetBall.started -= m_Wrapper.m_PachinkoInputsActionsCallbackInterface.OnResetBall;
                @ResetBall.performed -= m_Wrapper.m_PachinkoInputsActionsCallbackInterface.OnResetBall;
                @ResetBall.canceled -= m_Wrapper.m_PachinkoInputsActionsCallbackInterface.OnResetBall;
            }
            m_Wrapper.m_PachinkoInputsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ResetBall.started += instance.OnResetBall;
                @ResetBall.performed += instance.OnResetBall;
                @ResetBall.canceled += instance.OnResetBall;
            }
        }
    }
    public PachinkoInputsActions @PachinkoInputs => new PachinkoInputsActions(this);
    public interface IPachinkoInputsActions
    {
        void OnResetBall(InputAction.CallbackContext context);
    }
}
